import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const laquerFont = localFont({
  src: "./fonts/Lacquer.ttf",
  variable: "--font-lacquer",
  weight: "100 900"
})

const dancingScript = localFont({
  src: "./fonts/Dancing.ttf",
  variable: "--font-dancing",
  weight: "100 900"
})

const AmaticSC = localFont({
  src: "./fonts/AmaticSC.ttf",
  variable: "--font-amatic",
  weight: "100 900"
})

const GreatVibe = localFont({
  src: "./fonts/GreatVibes.ttf",
  variable: "--font-greatvibe",
  weight: "100 900"
})

const PoiretOne = localFont({
  src: "./fonts/PoiretOne.ttf",
  variable: "--font-poiret",
  weight: "100 900"
})

const Sacramento = localFont({
  src: "./fonts/Sacramento.ttf",
  variable: "--font-sacramento",
  weight: "100 900"
})

const Satisfy = localFont({
  src: "./fonts/Satisfy.ttf",
  variable: "--font-satisfy",
  weight: "100 900"
})

const Shadows = localFont({
  src: "./fonts/Shadows.ttf",
  variable: "--font-shadows",
  weight: "100 900"
})

const Sofia = localFont({
  src: "./fonts/Sofia.ttf",
  variable: "--font-sofia",
  weight: "100 900"
})

const jost = localFont({
  src: "./fonts/JostFont.ttf",
  variable: "--font-jost",
  weight: "100 900"
})

const poppins = localFont({
  src: "./fonts/Poppins.ttf",
  variable: "--font-poppins",
  weight: "100 900"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${laquerFont.variable}
          ${dancingScript.variable}
          ${GreatVibe.variable}
          ${AmaticSC.variable}
          ${PoiretOne.variable}
          ${Sacramento.variable}
          ${Satisfy.variable}
          ${Shadows.variable}
          ${Sofia.variable}
          ${poppins.variable}
          ${jost.variable}
          antialiased
          `}
      >
        {children}
      </body>
    </html>
  );
}
